plugins/cohere/package.json, plugins/mistral/package.json
Allow minor version bumps for Genkit dependencies for the Cohere and Mistral plugins.
N/A
=> Allow minor Genkit version changes for Mistral and Cohere

CONTRIBUTING.md
Fix some broken links on the contributing docs
N/A
=> Update broken links for CONTRIBUTING.md

plugins/anthropic/src/claude.ts
Add `text_delta` to the stream results. 
e.g. https://docs.anthropic.com/en/api/messages-streaming#basic-streaming-request
```
...
event: content_block_start
data: {"type": "content_block_start", "index": 0, "content_block": {"type": "text", "text": ""}}
event: content_block_delta
data: {"type": "content_block_delta", "index": 0, "delta": {"type": "text_delta", "text": "Hello"}}
event: content_block_stop
data: {"type": …
```
=> Anthropic - also stream text_delta

.github/workflows/main.yml, plugins/anthropic/src/claude.ts, sonar-project.properties
This PR configures SonarCloud in the repo, so that we can keep track of code quality in the future.
N/A
=> Configure SonarCloud

docs/docs/plugins/anthropic.md, package-lock.json, plugins/anthropic/README.md, plugins/anthropic/package.json, plugins/anthropic/src/claude.test.ts, plugins/anthropic/src/claude.ts, plugins/anthropic/src/index.ts
Added support for Claude 3.5 Sonnet model on Anthropic plugin.
Closes #94
=> [Anthropic] Add support for Claude 3.5 Sonnet model

plugins/openai/src/gpt.ts, plugins/openai/src/index.ts
=> Add gpt-4o-mini to OpenAI

plugins/graph/src/index.ts
In the graph impl there were one major and minor flaw:
1. there was no helper function to build output schema or flows (minor)
2. each node could _only_ either return state or output
This pr fixes that
=> Graph hotfix

plugins/graph/src/index.ts
- [ x ] I have read and understood the [contribution guidelines](https://github.com/TheFireCo/genkit-plugins/blob/main/CONTRIBUTING.md) and the [code of conduct](https://github.com/TheFireCo/genkit-plugins/blob/main/CODE_OF_CONDUCT.md);
Changes the sequence of parsing result to support cases stateschema and outputschema are not supplied so they are `any` by default
=> refactor(graph): support schemas being any

.github/CODEOWNERS, README.md, package-lock.json, plugins/azure-openai/README.md, plugins/azure-openai/package.json, plugins/azure-openai/src/dalle.ts, plugins/azure-openai/src/embedder.ts, plugins/azure-openai/src/gpt.ts, plugins/azure-openai/src/index.ts, plugins/azure-openai/src/tts.ts, plugins/azure-openai/src/whisper.ts
I added the Azure plugin with support for LLMs, embeddings, Whisper, tts, dalle3.
=> feat: azure-openai plugin

plugins/anthropic/src/index.ts
Export calude 3.5 hiaku
https://github.com/TheFireCo/genkit-plugins/issues/197
=> fix: export calude35haiku

package-lock.json, plugins/anthropic/package.json, plugins/azure-openai/README.md, plugins/azure-openai/package.json, plugins/azure-openai/src/gpt.ts, plugins/azure-openai/src/index.ts, plugins/cohere/package.json, plugins/groq/package.json, plugins/milvus/package.json, plugins/mistral/package.json, plugins/openai/package.json, plugins/openai/src/gpt.ts, plugins/openai/src/index.ts
- [x} I have added new tests (for bug fixes/features);
1. Prepare plugins for GA
2. Improve Azure open AI docs
3. added models to Azure OpenAI and OpenAI
=> feat: Genkit GA, changed docs and added more models

.all-contributorsrc, .github/CODEOWNERS, README.md
=> feat: force publish

docs/docs/plugins/groq.md, examples/groq/src/index.ts, lerna.json, package-lock.json, plugins/groq/README.md, plugins/groq/package.json, plugins/groq/src/groq_models.ts, plugins/groq/src/index.ts, plugins/groq/tests/groq_test.ts
Bumping groq to latest and adding/updating models
=> feat: bump groq and updating models

.github/workflows/npm_release.yml
=> fix: automation

plugins/openai/src/gpt.ts, plugins/openai/src/index.ts
=> OpenAI Gpt 4.5

docs/docs/plugins/anthropic.md, docs/docs/plugins/openai.md, plugins/azure-openai/src/gpt.ts, plugins/azure-openai/src/index.ts, plugins/openai/README.md
Added GPT-4.5 in azure-open ai plugin & docs updated
=> feat: gpt4.5

docs/docs/plugins/mistral.md, examples/mistral/package.json, examples/mistral/src/index.ts, package-lock.json, plugins/mistral/README.md, plugins/mistral/package.json, plugins/mistral/src/embedders.ts, plugins/mistral/src/index.ts, plugins/mistral/src/mistral_llms.ts, plugins/mistral/src/ocr.ts
Massive Mistral bump:
1. Update the client to latest version
2. Added all the new models (15 new models!)
3. Added Vision Capabilities
4. Added Mistral OCR
=> feat: mistral bump

docs/docs/plugins/openai.md, examples/openai/package.json, examples/openai/src/index.ts, package-lock.json, plugins/openai/README.md, plugins/openai/src/gpt.test.ts, plugins/openai/src/gpt.ts, plugins/openai/src/index.ts
Adds the ability to add custom models and also other cloud providers using the openai plugin
here is an example:
```typescript
import { GenerationCommonConfigSchema, genkit, z } from 'genkit';
import { ModelInfo } from 'genkit/model';
import openAI from 'genkitx-openai';
const modelInfo: ModelInfo = {
versions: ['claude-3-7-sonnet-20250219'],
label: 'Claude - Claude 3.7 Sonnet',
supports: {
multiturn: true,
tools: true, …
```
=> feat: made OpenAI plugin extensible

package-lock.json
=> fix: lockfile

examples/openai/src/index.ts, plugins/azure-openai/src/gpt.ts, plugins/openai/src/gpt.ts
Properties set in openai and azure openai plugin
=> fix: openai models properties

examples/azure-openai/src/index.ts, plugins/azure-openai/src/gpt.ts
fixes azure openai functions when it is in streaming mode
=> fix: azure openai functions

lerna.json, package-lock.json, plugins/azure-openai/package.json, plugins/azure-openai/src/whisper.ts
Azure openai needs opneai deps
=> fix: azure-openai needs openai too

plugins/azure-openai/src/gpt.ts, plugins/openai/src/gpt.ts
It displays the usage for streaming in Azure OpenAI and OpenAI plugins.
Related to issue #305
=> fix: usage while streaming on azure-openai and openai plugins (#305)

plugins/openai/src/gpt.test.ts
=> fix: tests

plugins/mistral/src/index.ts
As described in [Issue 316](https://github.com/TheFireCo/genkit-plugins/issues/316), there is currently no way to add custom models in the `genkitx-mistral` plugin.  This PR adds a `customModels` item to the constructor that can take in one or more custom models defined using `genkit/model`'s `modelRef` that can be used like this:
```typescript
import { GenerationCommonConfigSchema, genkit } from 'genkit';
import { modelRef } from 'genkit/model';
import mistral from 'genkitx-mistral';
export const customLarge2411 = modelRef({
name: 'mistral/mistral-large-2411',
info: {
versions: ['mistral-large-2411'],
label: 'Mistral - Mistral Large 2411',
supports: {
multiturn: true,
tools: true,
media: false, …
```
=> Added ability to define custom models in genkitx-mistral

plugins/anthropic/package.json, plugins/azure-openai/package.json
=> feat: bump versions
